[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "docker-django-example"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"

[pypi-dependencies]
django = ">=5.1.3, <6"
gunicorn = ">=23.0.0, <24"
whitenoise = ">=6.8.2, <7"
django-debug-toolbar = ">=4.4.6, <5"
redis = ">=5.2.0, <6"
celery = ">=5.4.0, <6"

setuptools = ">=75.6.0, <76"
psycopg2-binary = ">=2.9.10, <3"

[feature.dev.pypi-dependencies]
ruff = ">=0.8.0, <0.9"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }